version = 0.1
[default.deploy.parameters]
stack_name = "same-origin-example"
resolve_s3 = true
s3_prefix = "same-origin-example"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketName=\"sop-demo\" DomainName=\"sop.example.com\" HostedZoneId=\"ABC12346456\""
image_repositories = []
disable_rollback = true
