name: Deploy Sandbox

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name }}

permissions:
  id-token: write
  contents: read

env:
  STACK_NAME: oharkinsdev-cors

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.PIPELINE_EXECUTION_ROLE }}
          role-session-name: sam-deploy
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: SAM Build and Deploy
        run: |
          sam --info

          sam build \
          --config-file samconfig.ci.yaml \
          --config-env sandbox

          sam deploy \
          --stack-name $STACK_NAME \
          --config-file samconfig.ci.yaml \
          --config-env sandbox \
          --s3-bucket ${{ secrets.ARTIFACTS_BUCKET_NAME }} \
          --no-fail-on-empty-changeset \
          --role-arn ${{ secrets.CLOUDFORMATION_EXECUTION_ROLE }}

      - name: Get Stack Outputs
        run: |
          stackOutputJson=$(aws cloudformation describe-stacks --output json --stack-name $STACK_NAME --query "Stacks[0].Outputs")
          BucketName=$(echo $stackOutputJson | jq -r '.[] | select(.OutputKey=="BucketName") | .OutputValue')
          AppUiURL=$(echo $stackOutputJson | jq -r '.[] | select(.OutputKey=="AppUiURL") | .OutputValue')
          AppURL=$(echo $stackOutputJson | jq -r '.[] | select(.OutputKey=="AppURL") | .OutputValue')

          echo "# Outputs" >> $GITHUB_STEP_SUMMARY
          echo "* Bucket Name - $BucketName" >> $GITHUB_STEP_SUMMARY
          echo "* App UI URL - $AppUiURL" >> $GITHUB_STEP_SUMMARY
          echo "* App URL - $AppURL" >> $GITHUB_STEP_SUMMARY